name: Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write

jobs:
  documentation:
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Build
        run: |
          bash build.sh
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/pdoc
      - name: Deploy Pages
        uses: actions/deploy-pages@v2
